kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: jt-home
spec:
  entryPoints: 
    - websecure
  routes:
  - match: Host(`jtlewey.com`) 
    kind: Rule
    services:
    - name: home-chart
      port: 1337
  tls:
   certResolver: lets
   domains:
   - main: jtlewey.com